const ERROR_STATUS = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  TEAPOT: 418,
  UNPROCESSABLE_ENTITY: 422,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
};

module.exports = { ERROR_STATUS };
